# fly.toml file generated for fly-replay-header-demo on 2022-09-20T14:15:52-04:00

app = "fly-replay-header-demo"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.http_checks]]
    grace_period = "1s"
    interval = "15s"
    method = "get"
    path = "/health-check"
    protocol = "http"
    restart_limit = 0
    timeout = "2s"
    tls_skip_verify = true

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443
